### PR TITLE
Simplify the setting of COLESLAW-CONF:*BASEDIR*

### PR DESCRIPTION
**Pull request by PuercoPop**
No need to use a before method specializing in the LOAD-OP. Use uiop's
pathname-parent-directory-pathname instead

Hey, after reading your comment in https://github.com/kingcons/coleslaw/pull/111#issuecomment-249309025, I realized there was a simpler way to set the base-dir.

### CODE REVIEW

**Comment by PuercoPop** [comment]
Clearly I spoke to soon, and the brittle 'test' case broke 

```lisp
COLESLAW-CONF> *basedir*
#P"/home/puercopop/.cache/common-lisp/sbcl-1.3.6.121-a2d1969-linux-x64/home/puercopop/quicklisp/local-projects/coleslaw/"
```

**Comment by guicho271828** [comment]
looking into this

**Comment by guicho271828** [comment]
#180

**Comment by guicho271828** [comment]
`*load-truename*` does not work, it may point to the cached file.

**Comment by guicho271828** [comment]
looking into `#.(or *compile-file-truename* *load-truename*)` combo mentioned in xach's article.

**Comment by guicho271828** [comment]
test passed, merged, closed.

**Pull request closed without merging**
