### PR TITLE
roswell script

### PR DESCRIPTION
**Pull request by guicho271828**
+ Added a command line script (roswell script)
+ More friendly tutorial in the README (see https://github.com/guicho271828/coleslaw/tree/roswell )

Command line syntax:

```
Syntax:

coleslaw setup                       --- set up a new .coleslawrc file in the current directory.
coleslaw new [TYPE] [NAME]           --- creates a new content file with the correct format. TYPE defaults to 'post', NAME defaults to the current date.
coleslaw generate                    --- generates the static html according to .coleslawrc .
coleslaw copy-theme THEME [TARGET] --- copy the installed THEME in coleslaw to the current directory with a different name TARGET.
coleslaw                             --- shorthand of 'coleslaw generate'.
coleslaw -h                          --- show this help

Examples:

* set up a blog

    mkdir yourblog ; cd yourblog
    git init
    coleslaw setup
    git commit -a -m 'initial repo'

* Create a post

    coleslaw new

* Create a page (static page)

    coleslaw new page

* Generate a site

    coleslaw generate # or just: coleslaw

* Copy the base theme to the current directory for modification

    coleslaw copy-theme hyde mytheme

without renaming:
    coleslaw copy-theme hyde
```

### CODE REVIEW

**Comment by PuercoPop** [comment]
<3 The Roswell support, the PR is a little on the fat side. I'll review it over the week.

**Comment by guicho271828** [comment]
I should clean up the commit a little bit.

**Comment by guicho271828** [comment]
I first separate the bugfix PR.

**Comment by guicho271828** [comment]
but hey, I have time recently, I can help cleaning up the other PRs too

**Comment by guicho271828** [comment]
want to make this repo in a more healthy state

**Comment by guicho271828** [comment]
Cleaned up the commits,  hope I did nothing wrong during rebase.

**Comment by svetlyak40wt** [comment]
By the way, @guicho271828 what do you think about a https://github.com/40ants/defmain? This could be a good replacement for trivia in terms of command-line arguments parsing.

**Comment by guicho271828** [comment]
It is up to you, I believe you can choose to switch later.

**Comment by guicho271828** [comment]
I wish other, smaller PRs get merged first

**Comment by svetlyak40wt** [comment]
Actually, I'm not a repository's owner. Just decided to review interesting pull, because I've wrote a roswell script too, but it is much simpler than yours. I think it would be useful to have a command line utility out of the box.

**Comment by guicho271828** [comment]
I made the minimal changes since the the original 2-years old commits:
* Made the functions available from REPL (from `coleslaw-cli` package/system),
* Added README on both REPL usage and script usage

**Comment by guicho271828** [comment]
Also, minor changes:
* loading coleslaw-cli system causes printing a tutorial on the standard output (but only when `:swank` feature is found)
* don't load `:clack` dynamically (which will cause problem in quicklisp)

**Comment by guicho271828** [comment]
Both cli and repl commands have the unit test.

**Comment by guicho271828** [comment]
I guess it is fine now.

**Pull request merged**
